name = "meownote"  # 自定义 Worker 名称
main = "src/index.js"
compatibility_date = "2024-01-01"

assets = { directory = ".", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"  # 必须为 DB，不能改
database_name = "meownote-db"  # 自定义数据库名
database_id = "Your ID"  # 替换为实际 ID
